spring.application.name=car-sharing-service
spring.config.import=optional:file:.env[.properties]
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:3306/${MYSQLDB_DATABASE}?serverTimezone=UTC
spring.datasource.username=${MYSQLDB_USER}
spring.datasource.password=${MYSQLDB_ROOT_PASSWORD}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.servlet.context-path=/api
server.error.include-message=always
# Security & JWT
jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}
stripe.secret.key=${STRIPE_SECRET_KEY}
payment.success.url=${PAYMENT_SUCCESS_URL}
payment.cancel.url=${PAYMENT_CANCEL_URL}
telegrambots.enabled=true
telegrambots.bots[0].username=${TELEGRAM_BOT_NAME}
telegrambots.bots[0].token=${TELEGRAM_BOT_TOKEN}
admin.chat.id=${ADMIN_CHAT_ID}
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=alpha
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
