SET REFERENTIAL_INTEGRITY FALSE;
TRUNCATE TABLE users_roles;
TRUNCATE TABLE payments;
TRUNCATE TABLE rentals;
TRUNCATE TABLE users;
TRUNCATE TABLE cars;
TRUNCATE TABLE roles;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE cars ALTER COLUMN id RESTART WITH 1;
ALTER TABLE rentals ALTER COLUMN id RESTART WITH 1;
ALTER TABLE payments ALTER COLUMN id RESTART WITH 1;
SET REFERENTIAL_INTEGRITY TRUE;